import image from "./assets/paleo.jpg"

const testData = {
    id_fossil: 6,
    periods: [
        {
            id_period: 1,
            name: "Сидерий",
            description: "Первый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 2,
            name: "Рясий",
            description: "Второй период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 3,
            name: "Орозирий",
            description: "Третий период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 4,
            name: "Статерий",
            description: "Четвертый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 5,
            name: "Калимий",
            description: "Пятый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 6,
            name: "Эктазий",
            description: "Шестой период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 7,
            name: "Стений",
            description: "Седьмой период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 8,
            name: "Тоний",
            description: "Восьмой период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 9,
            name: "Криогений",
            description: "Девятый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 10,
            name: "Эдиакарий",
            description: "Десятый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 11,
            name: "Кембрий",
            description: "Одиннадцатый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 12,
            name: "Ордовик",
            description: "Двеннадцатый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 13,
            name: "Силурий",
            description: "Триннадцатый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 14,
            name: "Девон",
            description: "Четырнадцатый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 15,
            name: "Каменноугольный период",
            description: "Пятнадцатый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 16,
            name: "Пермь",
            description: "Шестнадцатый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 17,
            name: "Триас",
            description: "Семнадцатый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 18,
            name: "Юра",
            description: "Восемнадцатый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 19,
            name: "Мел",
            description: "Девятнадцатый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 20,
            name: "Палеоген",
            description: "Двадцатый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 21,
            name: "Неоген",
            description: "Двадцать первый период",
            age: "",
            status: "",
            photo: image,
        },
        {
            id_period: 22,
            name: "Четвертичный период",
            description: "Двадцать второй период",
            age: "",
            status: "",
            photo: image,
        },
    ]
}

export default testData;